version: '2'
services:
  mdm-storage:
    image: "supersede/mdm-storage"
    ports:
      - "8082:8082"
    depends_on:
      - "mongo"
    container_name: mdm-storage
  mdm-frontend:
    image: "supersede/mdm-frontend"
    ports:
      - "3001:3001"
    depends_on:
      - "mdm-storage"
    container_name: mdm-frontend
  mongo:
    image: "mongo:3.4.9"
    container_name: mongo
 
    