version: '2'
services:
  is:
    image: "supersede/is"
    ports:
      - "9445:9445"
    container_name: supersede-is
  esb:
    image: "supersede/esb"
    ports:
      - "9443:9443"
      - "8280:8280"
    depends_on:
      - "is"
    container_name: supersede-esb
  mysql:
    image: "supersede/mysql"
    container_name: supersede-mysql
  be:
    image: "supersede/be"
    ports:
      - "8081:8081"
    depends_on:
      - "esb"
      - "mysql"
      
      
      
      